# Generated by Django 4.2 on 2024-03-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('file', models.FileField(upload_to='certificate-documents/')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedCertificate',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('full_name', models.CharField(max_length=60)),
                (
                    'state',
                    models.CharField(
                        choices=[
                            ('AC', 'Acre'),
                            ('AL', 'Alagoas'),
                            ('AP', 'Amapá'),
                            ('AM', 'Amazonas'),
                            ('BA', 'Bahia'),
                            ('CE', 'Ceará'),
                            ('DF', 'Distrito Federal'),
                            ('ES', 'Espírito Santo'),
                            ('GO', 'Goiás'),
                            ('MA', 'Maranhão'),
                            ('MT', 'Mato Grosso'),
                            ('MS', 'Mato Grosso do Sul'),
                            ('MG', 'Minas Gerais'),
                            ('PA', 'Pará'),
                            ('PB', 'Paraíba'),
                            ('PR', 'Paraná'),
                            ('PE', 'Pernambuco'),
                            ('PI', 'Piauí'),
                            ('RJ', 'Rio de Janeiro'),
                            ('RN', 'Rio Grande do Norte'),
                            ('RS', 'Rio Grande do Sul'),
                            ('RO', 'Rondônia'),
                            ('RR', 'Roraima'),
                            ('SC', 'Santa Catarina'),
                            ('SP', 'São Paulo'),
                            ('SE', 'Sergipe'),
                            ('TO', 'Tocantins'),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    'certificate_type',
                    models.CharField(
                        choices=[
                            ('Military', 'Military'),
                            ('State', 'State'),
                            ('Labor', 'Labor'),
                            ('Federal', 'Federal'),
                        ],
                        max_length=20,
                    ),
                ),
                ('is_legal_entity', models.BooleanField()),
                ('vat', models.CharField(max_length=20)),
                ('service_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'full_name', 'state', 'certificate_type', 'is_legal_entity')},
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'document',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.document'),
                ),
                (
                    'request',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='certificates.requestedcertificate'
                    ),
                ),
            ],
        ),
    ]
