# Generated by Django 4.2 on 2024-03-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0003_alter_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificate-documents/'),
        ),
    ]
