# Generated by Django 4.2 on 2024-03-06 12:36

import common.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(
                blank=True, null=True, upload_to=common.storages.UniqueFilePathGenerator('certificate-documents/')
            ),
        ),
    ]
