# Generated by Django 4.2 on 2024-03-16 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0005_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                (
                    'available_person_type',
                    models.CharField(
                        choices=[
                            ('PF', 'Pessoa Física'),
                            ('PJ', 'Pessoa Jurídica'),
                            ('PF_PJ', 'Pessoa Física e Pessoa Jurídica'),
                        ],
                        max_length=50,
                    ),
                ),
                ('credits_needed', models.IntegerField()),
                ('deadline_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificateCategorie',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSubCategorie',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('status', models.CharField(choices=[('AN', 'Em andamento'), ('FN', 'Finalizado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890',
                        min_length=7,
                        prefix='',
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=20)),
                (
                    'uf',
                    models.CharField(
                        choices=[
                            ('AC', 'Acre'),
                            ('AL', 'Alagoas'),
                            ('AP', 'Amapá'),
                            ('AM', 'Amazonas'),
                            ('BA', 'Bahia'),
                            ('CE', 'Ceará'),
                            ('DF', 'Distrito Federal'),
                            ('ES', 'Espírito Santo'),
                            ('GO', 'Goiás'),
                            ('MA', 'Maranhão'),
                            ('MT', 'Mato Grosso'),
                            ('MS', 'Mato Grosso do Sul'),
                            ('MG', 'Minas Gerais'),
                            ('PA', 'Pará'),
                            ('PB', 'Paraíba'),
                            ('PR', 'Paraná'),
                            ('PE', 'Pernambuco'),
                            ('PI', 'Piauí'),
                            ('RJ', 'Rio de Janeiro'),
                            ('RN', 'Rio Grande do Norte'),
                            ('RS', 'Rio Grande do Sul'),
                            ('RO', 'Rondônia'),
                            ('RR', 'Roraima'),
                            ('SC', 'Santa Catarina'),
                            ('SP', 'São Paulo'),
                            ('SE', 'Sergipe'),
                            ('TO', 'Tocantins'),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requestedcertificate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.AddField(
            model_name='document',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='city_residence',
            field=models.CharField(default='default_city_residence', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(default='default_doc_id', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id_state',
            field=models.CharField(default='default_doc_id_state', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='father',
            field=models.CharField(default='default_father', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='gender',
            field=models.CharField(default='default_gender', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='marital_status',
            field=models.CharField(default='default_marital_status', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='mother',
            field=models.CharField(default='default_mother', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='default_name', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='rg',
            field=models.CharField(default='default_rg', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='rg_ssp',
            field=models.CharField(default='default_rg_ssp', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='social_security_number',
            field=models.CharField(default='default_social_security_number', max_length=50),
        ),
        migrations.AddField(
            model_name='requestedcertificate',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestedcertificate',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='IssuedCertificate',
        ),
        migrations.AddField(
            model_name='request',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.document'),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_certificates',
            field=models.ManyToManyField(to='certificates.requestedcertificate'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='court',
            name='states',
            field=models.ManyToManyField(to='certificates.state'),
        ),
        migrations.AddField(
            model_name='certificatecategorie',
            name='sub_categories',
            field=models.ManyToManyField(to='certificates.certificatesubcategorie'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatesubcategorie'
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='court',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.court'
            ),
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='certificate_type',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='is_legal_entity',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestedcertificate',
            name='vat',
        ),
        migrations.AddField(
            model_name='requestedcertificate',
            name='certificate',
            field=models.ForeignKey(
                default='0', on_delete=django.db.models.deletion.PROTECT, to='certificates.certificate'
            ),
        ),
    ]
