# Generated by Django 4.2 on 2024-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0008_certificate_sub_category_alter_certificate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
