# Generated by Django 4.2 on 2024-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('certificates', '0009_certificate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
