# Generated by Django 4.2 on 2024-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_userprofile_city_userprofile_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='certificate_credits',
            field=models.IntegerField(default=0),
        ),
    ]
