# Generated by Django 4.2 on 2024-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_userprofile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='vat',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
